import Head from 'next/head'
import { Hero } from '../components/layout/hero'

import { Wrapper } from 'components/atoms/wrapper/wrapper'
import { ProjectSection } from '@layout/project-section'
import { AboutSection } from '@layout/about-section'
import { StackSection } from '@layout/stack-section'
import { ContactSection } from '@layout/contact-section'
import { Footer } from '@molecules/footer'
import { MainStyled } from '../styles/globals'
import projectsJson from '@data/projects-home.json'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Alec Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <MainStyled>
        <Wrapper>
          <ProjectSection projects={projectsJson} />
          <AboutSection />
          <StackSection />
          <ContactSection />
          <Footer />
        </Wrapper>
      </MainStyled>
    </>
  )
}
