import Head from 'next/head'
import Contact from '../components/contact/contact'
import Footer from '../components/footer/footer'
import { Hero } from '../components/hero/hero'
import ListProject from '../components/projects/list-project/list-project'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Alec Portolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <main className={styles.main}>
        <div className='wrapper'>
          <div className={styles.main__content}>
            <ListProject />
          </div>
        </div>
      </main>
      <Contact />
      <Footer />
    </>
  )
}
