import Head from 'next/head'
import { Hero } from '../components/hero/hero'

import projectListJson from '@data/projects-home.json'
import { Wrapper } from 'components/wrapper/wrapper'
import { ProjectSection } from '@layout/project-section'
import { AboutSection } from '@layout/about-section'
import { StackSection } from '@layout/stack-section'
import { ContactSection } from '@layout/contact-section'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Alec Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <main>
        <Wrapper>
          <ProjectSection projects={projectListJson} />
          <AboutSection />
          <StackSection />
          <ContactSection />
        </Wrapper>
      </main>
    </>
  )
}
